# Generated by Django 5.2.3 on 2025-06-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0002_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="issue_prefix",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
