# Generated by Django 5.2 on 2025-05-05 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0002_organization_organizationmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(
                related_name="organizations",
                through="calyvim.OrganizationMember",
                through_fields=("organization", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
