# Generated by Django 5.2 on 2025-05-05 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0003_organization_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmember",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invited_organization_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
