# Generated by Django 5.2 on 2025-05-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0004_alter_organizationmember_invited_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
    ]
