# Generated by Django 5.2.3 on 2025-06-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0004_alter_state_sequence_issue_issuegoal_issuesnapshot_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="confirmed_at",
            new_name="date_joined",
        ),
    ]
