# Generated by Django 5.2.3 on 2025-06-27 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0005_rename_confirmed_at_user_date_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="domain",
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invited_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
