# Generated by Django 5.2.3 on 2025-06-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0006_remove_organization_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
