# Generated by Django 5.2.3 on 2025-06-27 02:21

import calyvim.models.fallbacks
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0007_user_is_anonymous"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="created_by",
            field=models.ForeignKey(
                on_delete=models.SET(calyvim.models.fallbacks.get_anonymous_user),
                related_name="created_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issuegoal",
            name="reviewed_by",
            field=models.ForeignKey(
                on_delete=models.SET(calyvim.models.fallbacks.get_anonymous_user),
                related_name="reviewed_goal_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                on_delete=models.SET(calyvim.models.fallbacks.get_anonymous_user),
                related_name="created_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=models.SET(calyvim.models.fallbacks.get_anonymous_user),
                related_name="organization_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(calyvim.models.fallbacks.get_anonymous_user),
                related_name="invited_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_by",
            field=models.ForeignKey(
                on_delete=models.SET(calyvim.models.fallbacks.get_anonymous_user),
                related_name="created_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
