# Generated by Django 5.2.3 on 2025-06-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0008_alter_issue_created_by_alter_issuegoal_reviewed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
