# Generated by Django 5.2.3 on 2025-06-27 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0009_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="users",
            field=models.ManyToManyField(
                related_name="teams",
                through="calyvim.TeamMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
