# Generated by Django 5.2.3 on 2025-06-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calyvim", "0010_team_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="color",
            field=models.CharField(default="#111111", max_length=7),
        ),
    ]
